name: Notify

on:
  workflow_run:
    workflows:
      - Build
    branches:
      - production
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions: read-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo GitHub Object
        run: echo ${{ toJson(github) }}
